### ISSUE TITLE
Request for source code for "Practical Swarm Intelligence in Python"

### ISSUE THREAD

**Issue by modafoe** [rkneusel9/MathForProgramming#1]
Dear Professor Ronald T. Kneusel,

My name is Alireza, and I am a Master's student at Qom University.

I am writing to ask for your assistance in obtaining the source code for your book Practical Swarm Intelligence in Python. I believe that this code would be a valuable resource for my research, as it would allow me to implement and test the algorithms and techniques that you describe in the book.

Also, my teacher (Professor Farjami) is also eagerly looking for these codes to explain them to his other students.

I understand that you may not be able to provide me with the code, but I would be grateful if you would consider my request.

Thank you for your time and consideration.

Sincerely,
Alireza Parchami

**Comment by rkneusel9** [comment]
Please email me directly at rkneuselbooks@gmail.com.  Thanks!

**Comment by modafoe** [comment]
Of course
thanks a lot.
